# Generated by Django 5.2.14 on 2026-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0005_add_previous_integration_identity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="controllerhistory",
            index=models.Index(
                fields=["controller", "-created_datetime"],
                name="control_con_control_b1bac5_idx",
            ),
        ),
    ]
