# Generated by Django 5.2.14 on 2026-05-31 15:22

import django.db.models.deletion
import hi.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0020_entity_allow_internal_attributes"),
        ("integrations", "0006_add_integration_is_paused"),
        ("location", "0006_add_locationattribute_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_id",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Integration Id"
                    ),
                ),
                (
                    "integration_name",
                    models.CharField(max_length=255, verbose_name="Integration Name"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "source_url",
                    models.URLField(max_length=2048, verbose_name="Source URL"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="MIME Type"
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hi.integrations.models._external_reference_upload_to,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(default=0, verbose_name="Order"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity External Reference",
                "verbose_name_plural": "Entity External References",
                "ordering": ["order_id", "-created_datetime"],
                "abstract": False,
                "unique_together": {("entity", "integration_id", "integration_name")},
            },
        ),
        migrations.CreateModel(
            name="LocationExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_id",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Integration Id"
                    ),
                ),
                (
                    "integration_name",
                    models.CharField(max_length=255, verbose_name="Integration Name"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "source_url",
                    models.URLField(max_length=2048, verbose_name="Source URL"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="MIME Type"
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hi.integrations.models._external_reference_upload_to,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(default=0, verbose_name="Order"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location External Reference",
                "verbose_name_plural": "Location External References",
                "ordering": ["order_id", "-created_datetime"],
                "abstract": False,
                "unique_together": {("location", "integration_id", "integration_name")},
            },
        ),
    ]
