# Generated by Django 5.2.14 on 2026-06-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Scene Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SimSceneBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_key",
                    models.CharField(max_length=96, verbose_name="Module Key"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator_profile.simprofile",
                        verbose_name="Profile",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="simulator_scenes.simscene",
                        verbose_name="Scene",
                    ),
                ),
            ],
            options={
                "ordering": ["module_key"],
                "unique_together": {("scene", "module_key")},
            },
        ),
        migrations.CreateModel(
            name="SimSceneControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_key",
                    models.CharField(max_length=96, verbose_name="Module Key"),
                ),
                (
                    "entity_name",
                    models.CharField(max_length=128, verbose_name="Entity Name"),
                ),
                (
                    "sim_state_id",
                    models.CharField(max_length=128, verbose_name="Sim State Id"),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(default=0, verbose_name="Order"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="simulator_scenes.simscene",
                        verbose_name="Scene",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id", "module_key", "entity_name"],
                "unique_together": {
                    ("scene", "module_key", "entity_name", "sim_state_id")
                },
            },
        ),
        migrations.CreateModel(
            name="SimStateSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("steps_json", models.JSONField(default=list, verbose_name="Steps")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_sequences",
                        to="simulator_scenes.simscene",
                        verbose_name="Scene",
                    ),
                ),
            ],
            options={
                "ordering": ["scene", "-updated_datetime"],
                "unique_together": {("scene", "name")},
            },
        ),
    ]
