# Generated by Django 5.2.14 on 2026-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator_scenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simstatesequence",
            name="initial_state_json",
            field=models.JSONField(default=list, verbose_name="Initial State"),
        ),
    ]
