# Generated by Django 5.2.14 on 2026-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nws", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nwssimalert",
            name="effective_offset_secs",
            field=models.IntegerField(
                default=-900,
                help_text='When the alert becomes effective, relative to "now" in seconds. Negative = in the past, positive = in the future.',
            ),
        ),
        migrations.AlterField(
            model_name="nwssimalert",
            name="expires_offset_secs",
            field=models.IntegerField(
                default=900,
                help_text='When the alert expires, relative to "now" in seconds.',
            ),
        ),
    ]
