# Generated by Django 5.2.14 on 2026-06-02 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nws", "0002_alter_nwssimalert_effective_offset_secs_and_more"),
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NwsSimConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_description",
                    models.CharField(
                        default="Partly Cloudy",
                        help_text="Short text shown for current conditions and forecast periods.",
                        max_length=64,
                    ),
                ),
                (
                    "temperature_c",
                    models.FloatField(
                        default=22.0,
                        help_text="Temperature °C (conditions and forecast).",
                    ),
                ),
                (
                    "dewpoint_c",
                    models.FloatField(default=12.0, help_text="Dew point °C."),
                ),
                (
                    "relative_humidity_pct",
                    models.IntegerField(
                        default=55,
                        help_text="Relative humidity (0-100%).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wind_speed_kmh",
                    models.FloatField(default=12.0, help_text="Wind speed in km/h."),
                ),
                (
                    "wind_direction_deg",
                    models.IntegerField(
                        default=200,
                        help_text="Wind direction degrees (forecast uses the nearest compass point).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "barometric_pressure_hpa",
                    models.FloatField(
                        default=1015.0,
                        help_text="Barometric pressure in hPa (emitted as Pa).",
                    ),
                ),
                (
                    "cloud_amount",
                    models.CharField(
                        choices=[
                            ("CLR", "CLR — Clear"),
                            ("FEW", "FEW — Few"),
                            ("SCT", "SCT — Scattered"),
                            ("BKN", "BKN — Broken"),
                            ("OVC", "OVC — Overcast"),
                        ],
                        default="SCT",
                        help_text="Sky cover for current conditions.",
                        max_length=3,
                    ),
                ),
                (
                    "precip_probability_pct",
                    models.IntegerField(
                        default=10,
                        help_text="Forecast probability of precipitation (0-100%).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_daytime",
                    models.BooleanField(
                        default=True,
                        help_text="Daytime flag for the first forecast period.",
                    ),
                ),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "sim_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nws_sim_conditions",
                        to="simulator_profile.simprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "NWS Sim Conditions",
                "verbose_name_plural": "NWS Sim Conditions",
            },
        ),
    ]
