# Generated by Django 5.2.14 on 2026-06-02 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SunriseSunsetSimState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sunrise",
                    models.CharField(
                        default="06:00",
                        help_text="Local sunrise time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "sunset",
                    models.CharField(
                        default="20:00",
                        help_text="Local sunset time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "solar_noon",
                    models.CharField(
                        default="13:00",
                        help_text="Local solar-noon time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "utc_offset_hours",
                    models.IntegerField(
                        default=0,
                        help_text="Set to your main-app console UTC offset (e.g. -5 for EST) so the times above display as entered. The API returns UTC instants that the main app re-localizes; 0 emits the times as UTC.",
                    ),
                ),
                (
                    "status_str",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("INVALID_REQUEST", "INVALID_REQUEST"),
                            ("INVALID_DATE", "INVALID_DATE"),
                            ("UNKNOWN_ERROR", "UNKNOWN_ERROR"),
                            ("INVALID_TZID", "INVALID_TZID"),
                        ],
                        default="OK",
                        help_text="Top-level API status. Anything but OK exercises the main-app error path.",
                        max_length=24,
                    ),
                ),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "sim_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunrise_sunset_sim_state",
                        to="simulator_profile.simprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunrise-Sunset Sim State",
                "verbose_name_plural": "Sunrise-Sunset Sim States",
            },
        ),
    ]
