# Generated by Django 5.2.14 on 2026-05-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_add_eventclause_value_operator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventclause",
            options={
                "verbose_name": "Rule Condition",
                "verbose_name_plural": "Rule Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="eventdefinition",
            options={"verbose_name": "Rule", "verbose_name_plural": "Rules"},
        ),
        migrations.AlterModelOptions(
            name="eventhistory",
            options={
                "ordering": ["-event_datetime"],
                "verbose_name": "Rule Match",
                "verbose_name_plural": "Rule Matches",
            },
        ),
        migrations.AlterField(
            model_name="alarmaction",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_actions",
                to="event.eventdefinition",
                verbose_name="Rule",
            ),
        ),
        migrations.AlterField(
            model_name="controlaction",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_actions",
                to="event.eventdefinition",
                verbose_name="Rule",
            ),
        ),
        migrations.AlterField(
            model_name="eventclause",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_clauses",
                to="event.eventdefinition",
                verbose_name="Rule",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="event_type_str",
            field=models.CharField(max_length=32, verbose_name="Match Type"),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="event_window_secs",
            field=models.PositiveIntegerField(verbose_name="Match Window Secs"),
        ),
        migrations.AlterField(
            model_name="eventhistory",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="event.eventdefinition",
                verbose_name="Rule",
            ),
        ),
    ]
