# Generated by Django 5.2.14 on 2026-06-02 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenMeteoSimState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature_c",
                    models.FloatField(
                        default=22.0,
                        help_text="Temperature °C (current, hourly, and daily high).",
                    ),
                ),
                (
                    "temperature_min_c",
                    models.FloatField(
                        default=14.0,
                        help_text="Daily low temperature °C (daily forecast and archive).",
                    ),
                ),
                (
                    "relative_humidity_pct",
                    models.IntegerField(
                        default=55,
                        help_text="Relative humidity (0-100%).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "dewpoint_c",
                    models.FloatField(
                        default=12.0, help_text="Dew point °C (current conditions)."
                    ),
                ),
                (
                    "precipitation_mm",
                    models.FloatField(
                        default=0.0,
                        help_text="Precipitation in mm (per hour / daily sum).",
                    ),
                ),
                (
                    "pressure_msl_hpa",
                    models.FloatField(
                        default=1015.0,
                        help_text="Mean sea-level pressure in hPa (current conditions).",
                    ),
                ),
                (
                    "windspeed_kmh",
                    models.FloatField(default=12.0, help_text="Wind speed in km/h."),
                ),
                (
                    "winddirection_deg",
                    models.IntegerField(
                        default=200,
                        help_text="Wind direction in degrees (0-360).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "weathercode",
                    models.IntegerField(
                        choices=[
                            (0, "0 — Clear sky"),
                            (1, "1 — Mainly clear"),
                            (2, "2 — Partly cloudy"),
                            (3, "3 — Overcast"),
                            (45, "45 — Fog"),
                            (48, "48 — Depositing rime fog"),
                            (51, "51 — Light drizzle"),
                            (53, "53 — Moderate drizzle"),
                            (55, "55 — Dense drizzle"),
                            (61, "61 — Slight rain"),
                            (63, "63 — Moderate rain"),
                            (65, "65 — Heavy rain"),
                            (66, "66 — Light freezing rain"),
                            (71, "71 — Slight snow"),
                            (73, "73 — Moderate snow"),
                            (75, "75 — Heavy snow"),
                            (80, "80 — Slight rain showers"),
                            (81, "81 — Moderate rain showers"),
                            (82, "82 — Violent rain showers"),
                            (85, "85 — Slight snow showers"),
                            (95, "95 — Thunderstorm"),
                            (96, "96 — Thunderstorm with slight hail"),
                        ],
                        default=1,
                        help_text="WMO weather code; the main app maps it to a description.",
                    ),
                ),
                (
                    "is_day",
                    models.BooleanField(
                        default=True, help_text="Daytime flag for current conditions."
                    ),
                ),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "sim_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openmeteo_sim_state",
                        to="simulator_profile.simprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open-Meteo Sim State",
                "verbose_name_plural": "Open-Meteo Sim States",
            },
        ),
    ]
