# Generated by Django 5.2.14 on 2026-06-02 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsnoSimState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sunrise",
                    models.CharField(
                        default="05:44",
                        help_text="Local sunrise time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "sunset",
                    models.CharField(
                        default="20:28",
                        help_text="Local sunset time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "solar_noon",
                    models.CharField(
                        default="13:06",
                        help_text="Local solar-noon (upper-transit) time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "moonrise",
                    models.CharField(
                        default="22:55",
                        help_text="Local moonrise time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "moonset",
                    models.CharField(
                        default="07:06",
                        help_text="Local moonset time (HH:MM).",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a time as HH:MM (24-hour).",
                                regex="^\\d{1,2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "fracillum_percent",
                    models.IntegerField(
                        default=95,
                        help_text="Moon illuminated fraction (0-100%).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "curphase_str",
                    models.CharField(
                        choices=[
                            ("New Moon", "New Moon"),
                            ("Waxing Crescent", "Waxing Crescent"),
                            ("First Quarter", "First Quarter"),
                            ("Waxing Gibbous", "Waxing Gibbous"),
                            ("Full Moon", "Full Moon"),
                            ("Waning Gibbous", "Waning Gibbous"),
                            ("Last Quarter", "Last Quarter"),
                            ("Waning Crescent", "Waning Crescent"),
                        ],
                        default="Waning Gibbous",
                        help_text="Current moon phase; drives the waxing/waning flag.",
                        max_length=24,
                    ),
                ),
                (
                    "tz_offset_hours",
                    models.IntegerField(
                        default=0,
                        help_text="Cosmetic tz value echoed in the payload; the main app ignores it.",
                    ),
                ),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                (
                    "sim_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usno_sim_state",
                        to="simulator_profile.simprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "USNO Sim State",
                "verbose_name_plural": "USNO Sim States",
            },
        ),
    ]
